language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run cover

before_install:
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
- npm install -g greenkeeper-lockfile

before_script:
  - greenkeeper-lockfile-update

# Send coverage data to Coveralls
after_script: 
  - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
  - greenkeeper-lockfile-upload