language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run cover

before_install:
  - yarn global add greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

# Send coverage data to Coveralls
after_script: 
  - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
  - greenkeeper-lockfile-upload